"""add average cost before sale to transactions

Revision ID: 03e5cde5c394
Revises: 33bc04cf8fea
Create Date: 2026-08-03 20:39:52.115620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03e5cde5c394'
down_revision = '33bc04cf8fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_cost_before_sale', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('average_cost_before_sale')

    # ### end Alembic commands ###
