"""Add tables that already exist in Supabase

ここで作るテーブルは Supabase 上に手で構築済みで、この revision はその状態を
Alembic の初期リビジョンとして写し取ったもの。既存の DB（本番の Supabase）は
`flask db stamp 2fb34ddaba88` 済みで、upgrade が流れることはない。まっさらな
DB を立てるときだけ実際に実行される。

その新規 DB 向けに 1 点補足。`public.users.id` から `auth.users.id` への外部キー
users_id_fkey はここに含まれていない。auth スキーマは Supabase Auth の管理下で
アプリのマイグレーション対象外だからで、必要なら別途張ること。

Revision ID: 2fb34ddaba88
Revises:
Create Date: 2026-08-01 02:47:42.458680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb34ddaba88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_type',
    sa.Column('id', sa.Uuid(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('asset_type', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='asset_type_pkey')
    )
    op.create_table('currency',
    sa.Column('id', sa.Uuid(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='currency_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    op.create_table('asset_master',
    sa.Column('id', sa.Uuid(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('asset_type_id', sa.Uuid(), server_default=sa.text('(gen_random_uuid())'), nullable=True),
    sa.Column('currency_id', sa.Uuid(), server_default=sa.text('(gen_random_uuid())'), nullable=True),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_type.id'], name='asset_master_asset_type_id_fkey'),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], name='asset_master_currency_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='asset_master_pkey')
    )
    op.create_table('portfolio',
    sa.Column('id', sa.Uuid(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('user_id', sa.Uuid(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('name', sa.Text(), server_default=sa.text("('Default Portfolio'::text)"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='portfolio_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='portfolio_pkey'),
    sa.UniqueConstraint('user_id', name='portfolio_user_id_key')
    )
    op.create_table('asset_data_history',
    sa.Column('id', sa.Uuid(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('close_price', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_master.id'], name='asset_data_history_asset_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='asset_data_history_pkey'),
    sa.UniqueConstraint('asset_id', 'price_date', name='asset_data_history_asset_id_price_date_key')
    )
    op.create_index('asset_data_history_asset_id_price_date_idx', 'asset_data_history', ['asset_id', sa.text('price_date DESC')], unique=False)
    op.create_table('holdings',
    sa.Column('id', sa.Uuid(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False),
    sa.Column('average_cost', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_master.id'], name='holdings_asset_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], name='holdings_portfolio_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='holdings_pkey'),
    sa.UniqueConstraint('portfolio_id', 'asset_id', name='holdings_portfolio_id_asset_id_key')
    )
    op.create_index('holdings_asset_id_idx', 'holdings', ['asset_id'], unique=False)
    op.create_index('holdings_portfolio_id_idx', 'holdings', ['portfolio_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('holding_id', sa.Uuid(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('fees', sa.Numeric(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=False),
    sa.Column('transaction_type', sa.Text(), server_default=sa.text("(''::text)"), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], name='transactions_holding_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='transactions_pkey')
    )
    op.create_index('transactions_holding_id_idx', 'transactions', ['holding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('transactions_holding_id_idx', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('holdings_portfolio_id_idx', table_name='holdings')
    op.drop_index('holdings_asset_id_idx', table_name='holdings')
    op.drop_table('holdings')
    op.drop_index('asset_data_history_asset_id_price_date_idx', table_name='asset_data_history')
    op.drop_table('asset_data_history')
    op.drop_table('portfolio')
    op.drop_table('asset_master')
    op.drop_table('users')
    op.drop_table('currency')
    op.drop_table('asset_type')
    # ### end Alembic commands ###
